-- create new TYPE called grocery and 
-- new TABLE called shopping_list.
-- TABLE should contain 6 columns with
-- data from seed file.
-- grocery TYPE is ENUM (Main, Snack, Lunch, Breakfast)
-- Shopping_list(no null): id, name, price, date_added, checked, category.

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price DECIMAL(5,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    category grocery NOT NULL
);