INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('Fish can''t swim',                                             now() - '0 days'::INTERVAL, 'Ut consectetur et ut laborum exercitation ullamco labore. Aliqua qui reprehenderit reprehenderit veniam labore ipsum adipisicing irure aliquip. Enim aute dolor cillum culpa culpa commodo cillum laboris id.'),
    ('You know what smells?',                                        now() - '0 days'::INTERVAL, 'Elit fugiat nostrud enim do sint. Laboris id consequat consectetur ut fugiat duis eiusmod esse non tempor id eu. Occaecat elit aliquip Lorem non fugiat eu irure nostrud dolore voluptate mollit. Sit culpa ut enim mollit quis consectetur quis irure dolore. Amet duis magna exercitation ex exercitation eu do velit magna quis fugiat mollit labore nostrud. Lorem excepteur cillum nisi veniam pariatur aute proident. Nostrud excepteur aliquip ex duis.'),
    ('feelings are for ...my stomach?',                              now() - '1 days'::INTERVAL, 'In sint incididunt magna elit. Consectetur sunt consequat est non nisi officia quis. Ea laboris esse adipisicing consectetur sit duis minim et.'),
    ('6 ways to blow s#*t up!',                                      now() - '2 days'::INTERVAL, 'Ad mollit aute duis sit aute dolore cillum ad duis. Nulla aute non ex labore excepteur aute dolore. Ad id in occaecat laborum. Do ut anim dolor et excepteur sunt nisi dolore anim.'),
    ('Hit my baby, no more times!',                                  now() - '3 days'::INTERVAL, 'Occaecat est amet dolore minim pariatur nostrud consectetur occaecat magna ea labore nostrud incididunt culpa. Occaecat id incididunt pariatur anim amet sint id officia in nulla deserunt qui. Veniam commodo aliqua in esse eu aliqua veniam nulla Lorem occaecat. Incididunt commodo ad excepteur eiusmod. Magna dolor velit sunt ad dolor culpa qui aliqua cupidatat consectetur eu ex.'),
    ('A jewish guy walks into a bar, buys a drink ...that''s it.',   now() - '5 days'::INTERVAL, 'Sunt eu eu nulla veniam. Ullamco deserunt officia id in id esse amet commodo cupidatat et voluptate mollit anim cillum. Minim ex cillum eiusmod excepteur ullamco. Enim nulla non duis aliqua incididunt anim esse anim consequat.'),
    ('What your favorite pizza says about your sex life...',         now() - '7 days'::INTERVAL, 'Sit qui laboris culpa culpa id velit nostrud mollit incididunt aliqua consectetur exercitation eu. Irure ad fugiat occaecat consequat esse ad excepteur consequat reprehenderit do. Quis aliquip ullamco anim laborum. Dolor nostrud occaecat dolore sunt eu adipisicing incididunt ex cillum officia. Est cillum incididunt voluptate in ex magna ipsum.'),
    ('Hit the road Jack, and wait, where''d you go?',                now() - '8 days'::INTERVAL, 'Dolor pariatur aute adipisicing incididunt velit esse dolore ad. Duis nulla tempor laborum dolore mollit ullamco laborum dolore veniam ea duis dolor. Duis eu velit nisi sit laborum culpa magna aute. Ex qui labore laboris esse sit officia officia. Non minim non mollit qui. Aliquip quis tempor eu velit.'),
    ('This isn''t how it looks, but it never is.',                   now() - '9 days'::INTERVAL, 'Occaecat do adipisicing eu consectetur ex cillum ut consequat nulla nulla veniam quis sunt nisi. Elit et tempor ipsum aute. Veniam voluptate qui sunt nulla ut. Excepteur est nostrud cupidatat anim aliquip magna sunt ullamco incididunt commodo.')
;